name: Python Tests

on:
  push:
    branches:
      - CICD

  pull_request:
    branches:
      - CICD

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t supermercado-tests .

      - name: Ejecutar tests en Docker
        run: docker run supermercado-tests